baseURL = "https://talentaccurate.com.com/"
languageCode = "en-us"
title = "Raja CSP Raman"
theme = "berbera"

pygmentsCodeFences=true
pygmentsUseClasses=true
canonifyURLs=true
publishDir="docs"
disableKinds = ["section", "taxonomy", "taxonomyTerm"]
